### ISSUE TITLE
Not Working in Team

### ISSUE THREAD

**Issue by MuhammadArif7** [YannickRe/spfx-msgraph-peoplesearch#32] opened 2021-08-26 07:50 UTC
Working perfectly in SharePoint in the browser. But not working through the team app on mobile.

**Comment by sirarif** [comment] 2021-09-02 04:53
After successfully added in SharePoint modern communication page. I link the SharePoint site in Microsoft team. Team app installed in mobile and test then this WebPart do not show any think.

**Comment by YannickRe** [comment] 2021-09-02 07:06
There are multiple ways to "link the SharePoint site in Teams", can you be a bit more specific? Is it with Viva Connections desktop, a tab in a specific team (and is that with the Website app or the Pages app).
I really need to know the specifics because every app, and every method makes the page behave differently :)

**Comment by KarolFilipKozlowski** [comment] 2021-12-08 07:24
Hello, any new info or version? Like sirarif at my team, I have a simple tab. I used tab a page SharePoint. Below search bar some time, some user had just a red bar with no message.

**Comment by YannickRe** [comment] 2024-01-10 20:34
Closing this. Can no longer reproduce this, and in the mean time this web part, the Teams mobile app, and SharePoitn have gotten various updates. If this issue still persists, feel free to open a new issue.

**Closed by YannickRe** 2024-01-10 20:34 UTC
Labels: bug
