### ISSUE TITLE
Problem using SharePoint Mobile App on Android and IOS

### ISSUE THREAD

**Issue by cordapse** [YannickRe/spfx-msgraph-peoplesearch#40] opened 2021-11-10 14:44 UTC
Hi
The webpart works fine in a browser but when it is viewed inside the SharePoint Mobile App we just get a red cross in the app where the webpart should be.
Any ideas how to get around this?

Thanks

**Comment by YannickRe** [comment] 2021-11-11 09:34
Hi @cordapse, I'm sorry that you are hitting this issue.
I currently cannot reproduce this issue, it works without issue on my iPhone 12 inside the SharePoint Mobile app.

Some checks you can do:

- Are you running the latest version of the web part (from this repository?)
- Are you running the latest version of the SharePoint mobile app?
- Could you try visiting the SharePoint Admin Center API Approval page? I heard people that did this with similar issues, and they went away afterwards.

**Comment by YannickRe** [comment] 2024-01-10 20:36
Closing this. Can no longer reproduce this and in the meantime, this web part, the Teams mobile app, and SharePoint have gotten various updates. If this issue still persists, feel free to open a new issue.

**Closed by YannickRe** 2024-01-10 20:36 UTC
Labels: bug
